### PR TITLE
#144 SOAP1.2 support

### PR DESCRIPTION
**Pull request by kusmierz**
It should allow to use SOAP 1.2 binding. By default it uses 1.1 as before.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @kusmierz,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by kusmierz** [comment]
signed CLA

**Comment by renatocaval** [comment]
@ihostage, any reason for keeping it with `block-merge`?

**Comment by ihostage** [comment]
Fixes https://github.com/playframework/play-soap/issues/144

**Comment by ihostage** [comment]
Hi, @renatocaval! 
It was blocked to merge because I wanted to analyze this problem more detailed.
I think, that server must explicitly describe soap 1.2 bindings for his methods in WSDL and it not need to manually configure on the client-side. (for example https://stackoverflow.com/questions/736845/can-a-wsdl-indicate-the-soap-version-1-1-or-1-2-of-the-web-service)

I don't mind to merge this PR and add one property to client config. Just I think, that it's incorrect solve of the root problem 😄

**Comment by ihostage** [comment]
By the way, now we know that `block-merge` does not work. 😂

**Comment by renatocaval** [comment]
Mergify is configure for label `status:block-merge`, not `block-merge`. 🤦 

We can revert the commit. If that's not needed, better to not have extra code.

**Pull request merged**
